# エイリアス定義
alias ls='eza -la'
alias l='ls'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias lg='lazygit'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias emacs='nvim'
alias nano='nvim'
alias :q='exit'
alias c='clear'
alias g='git'
alias gpl='git pull'
alias gps='git push'
alias gc='git checkout'
alias tree='tree -N'

