return {
	-- "shellRaining/hlchunk.nvim",
	-- event = { "BufReadPre", "BufNewFile" },
	-- config = function()
	-- 	require("hlchunk").setup({
	-- 		chunk = {
	-- 			enable = true,
	-- 			notify = true,
	-- 			chars = {
	-- 				horizontal_line = "─",
	-- 				vertical_line = "│",
	-- 				left_top = "╭",
	-- 				left_bottom = "╰",
	-- 				right_arrow = ">",
	-- 			},
	-- 			use_treesitter = true,
	-- 		},
	-- 		line_num = {
	-- 			enable = true,
	-- 			use_treesitter = true,
	-- 		},
	-- 	})
	-- end,
}
